export const queryKeys = {
  me: ['me'] as const,
  crops: (filter?: Record<string, any>) => ['crops', filter] as const,
  cropDetail: (id: number) => ['crops', id] as const,
  farms: ['farms'] as const,
  farmDetail: (id: string) => ['farms', id] as const,
  farmWeather: (id: string) => ['farms', id, 'weather'] as const,
  advisories: ['advisories'] as const,
  advisoryDetail: (id: string) => ['advisories', id] as const,
  recommendations: ['recommendations'] as const,
  recommendationDetail: (id: string) => ['recommendations', id] as const,
  diagnoses: ['diagnoses'] as const,
  diagnosisDetail: (id: string) => ['diagnoses', id] as const,
  fertilizers: ['fertilizers'] as const,
  fertilizerDetail: (id: string) => ['fertilizers', id] as const,
  chatSessions: ['chat', 'sessions'] as const,
  chatMessages: (sessionId: string) => ['chat', 'sessions', sessionId, 'messages'] as const,
  history: (query?: Record<string, any>) => ['history', query] as const,
  usageToday: ['usage', 'today'] as const,
};
