export const AVAILABLE_FERTILIZERS = {
    urea: {
        id: 'urea',
        name: 'Urea (46-0-0)',
        category: 'chemical',
        nPercent: 46.0,
        pPercent: 0,
        kPercent: 0,
        description: 'High-nitrogen granular synthetic fertilizer supplying 46% N.',
    },
    dap: {
        id: 'dap',
        name: 'DAP - Di-Ammonium Phosphate (18-46-0)',
        category: 'chemical',
        nPercent: 18.0,
        pPercent: 46.0,
        kPercent: 0,
        description: 'Provides 18% N and 46% P2O5; primary basal phosphate source.',
    },
    mop: {
        id: 'mop',
        name: 'MOP - Muriate of Potash (0-0-60)',
        category: 'chemical',
        nPercent: 0,
        pPercent: 0,
        kPercent: 60.0,
        description: 'Standard potassium chloride fertilizer with 60% K2O.',
    },
    ssp: {
        id: 'ssp',
        name: 'SSP - Single Super Phosphate (0-16-0 + 11% S)',
        category: 'chemical',
        nPercent: 0,
        pPercent: 16.0,
        kPercent: 0,
        description: 'Supplies 16% P2O5 along with 11% Sulphur and 19% Calcium.',
    },
    npk_10_26_26: {
        id: 'npk_10_26_26',
        name: 'NPK 10:26:26',
        category: 'chemical',
        nPercent: 10.0,
        pPercent: 26.0,
        kPercent: 26.0,
        description: 'Complex fertilizer well-suited for root development and potash feeding.',
    },
    npk_12_32_16: {
        id: 'npk_12_32_16',
        name: 'NPK 12:32:16',
        category: 'chemical',
        nPercent: 12.0,
        pPercent: 32.0,
        kPercent: 16.0,
        description: 'Complex fertilizer ideal for basal dressing across cereal crops.',
    },
    ammonium_sulphate: {
        id: 'ammonium_sulphate',
        name: 'Ammonium Sulphate (20.5-0-0 + 24% S)',
        category: 'chemical',
        nPercent: 20.5,
        pPercent: 0,
        kPercent: 0,
        description: 'Provides ammoniacal nitrogen along with 24% sulphur.',
    },
    fym: {
        id: 'fym',
        name: 'Farm Yard Manure / Compost (FYM)',
        category: 'organic',
        nPercent: 0.5,
        pPercent: 0.25,
        kPercent: 0.5,
        description: 'Well-decomposed cattle manure improving soil organic carbon.',
    },
    vermicompost: {
        id: 'vermicompost',
        name: 'Vermicompost',
        category: 'organic',
        nPercent: 1.5,
        pPercent: 1.0,
        kPercent: 1.5,
        description: 'Earthworm cast rich in organic matter and beneficial microflora.',
    },
};
export const FERTILIZER_KEYS = [
    'urea',
    'dap',
    'mop',
    'ssp',
    'npk_10_26_26',
    'npk_12_32_16',
    'ammonium_sulphate',
    'fym',
    'vermicompost',
];
